apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-setting
  namespace: wordpress-stack
  labels:
     app.kubernetes.io/name: filebrowser
     app.kubernetes.io/creator: hossein-yousefi
     app.kubernetes.io/stack: wordpress
     app.kubernetes.io/env: production
data: 
  settings: |
   {
     "port": 80,
     "baseURL": "",
     "log": "stdout",
     "address": "0.0.0.0",
     "database": "/database.db",
     "root": "/srv"
    }

