apiVersion: v1
kind: Service
metadata:
  namespace: wordpress-stack
  name: filebrowser
  labels:
     app.kubernetes.io/name: filebrowser
     app.kubernetes.io/creator: hossein-yousefi
     app.kubernetes.io/stack: wordpress
     app.kubernetes.io/env: production
spec:
  ports:
    - port: 80
  selector:
     app.kubernetes.io/name: filebrowser
     app.kubernetes.io/creator: hossein-yousefi
     app.kubernetes.io/stack: wordpress
     app.kubernetes.io/env: production
  type: ClusterIP

