apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pma-pv-claim
  namespace: wordpress-stack
  labels:
    app.kubernetes.io/name: phpmyadmin
    app.kubernetes.io/creator: hossein-yousefi
    app.kubernetes.io/stack: wordpress
    app.kubernetes.io/env: production

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs
