apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: wordpress-stack
  name: wp-pv-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: glusterfs 
