apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: wordpress-stack
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  
  - host: hosein.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wordpress
            port:
              number: 80
              
  - host: phpmyadmin.hosein.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: phpmyadmin
            port:
              number: 80
              
  - host: file.hosein.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: filebrowser
            port:
              number: 80
              
  - host: mail.hosein.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: poste
            port:
              number: 80    


              
