apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: wordpress-stack
  labels:
     app.kubernetes.io/name: mysql-config
     app.kubernetes.io/creator: hossein-yousefi
     app.kubernetes.io/stack: wordpress
     app.kubernetes.io/env: production
data:
  default_auth: |
    [mysqld]
    bind-address= 0.0.0.0


